export class GameAudio{
 constructor(){this.ctx=null;this.muted=false;this.lastImpact=0;}
 start(map=0){if(!this.ctx){this.ctx=new AudioContext();this.master=this.ctx.createGain();this.master.gain.value=this.muted?0:.55;this.master.connect(this.ctx.destination);const buffer=this.ctx.createBuffer(1,this.ctx.sampleRate*2,this.ctx.sampleRate),d=buffer.getChannelData(0);let brown=0;for(let i=0;i<d.length;i++){brown=(brown+(Math.random()*2-1)*.02)/1.02;d[i]=brown*3.5;}this.noise=buffer;this.ambient=this.ctx.createGain();this.ambient.gain.value=.027;this.ambient.connect(this.master);const n=this.ctx.createBufferSource();n.buffer=buffer;n.loop=true;const lp=this.ctx.createBiquadFilter();lp.type='lowpass';lp.frequency.value=260;n.connect(lp);lp.connect(this.ambient);n.start();this.drone=this.ctx.createOscillator();this.drone.type='sine';this.drone.frequency.value=55;const gain=this.ctx.createGain();gain.gain.value=.014;this.drone.connect(gain);gain.connect(this.ambient);this.drone.start();}this.ctx.resume();this.setMap(map);}
 setMap(map){if(this.drone)this.drone.frequency.setTargetAtTime([55,47,73.4,65.4,41.2,82.4][map]||55,this.ctx.currentTime,.5);}
 toggle(){this.muted=!this.muted;if(this.master)this.master.gain.setTargetAtTime(this.muted?0:.55,this.ctx.currentTime,.1);return this.muted;}
 impact(force=5){if(!this.ctx)return;const t=this.ctx.currentTime;if(t-this.lastImpact<.045)return;this.lastImpact=t;const f=Math.min(1,force/15);const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.frequency.setValueAtTime(110+f*50,t);o.frequency.exponentialRampToValueAtTime(32,t+.15);g.gain.setValueAtTime(.06+f*.24,t);g.gain.exponentialRampToValueAtTime(.001,t+.22);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+.24);this.burst(.07,.12*f,350);}
 burst(duration=.1,volume=.12,cutoff=900){if(!this.ctx)return;const t=this.ctx.currentTime,n=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();n.buffer=this.noise;f.type='bandpass';f.frequency.value=cutoff;f.Q.value=.7;g.gain.setValueAtTime(volume,t);g.gain.exponentialRampToValueAtTime(.001,t+duration);n.connect(f);f.connect(g);g.connect(this.master);n.start(t);n.stop(t+duration+.01);}
 voice(text='SIKTR!',who=0){if(!this.ctx)return;const t=this.ctx.currentTime,ctx=this.ctx;const pitch=(.7+Math.random()*.6)*(who===3?1.3:1);const sequences={'SIKTR!':[[350,2100,.06],[430,1650,.13],[280,1100,.12]],'NOPE!':[[500,1050,.16],[360,850,.12]],'OUT!':[[800,1200,.16],[350,750,.14]],'GET LOST!':[[550,1900,.1],[400,900,.09],[800,1150,.16]],'GO AWAY!':[[500,900,.1],[730,1100,.11],[530,1850,.17]]};const vowels=sequences[text]||sequences['SIKTR!'];const osc=ctx.createOscillator();osc.type='sawtooth';osc.frequency.setValueAtTime((115+who*10)*pitch,t);osc.frequency.exponentialRampToValueAtTime(82*pitch,t+.45);const env=ctx.createGain();env.gain.value=.001;osc.connect(env);let offset=0;for(const [f1,f2,duration] of vowels){for(const [freq,amp] of [[f1,.55],[f2,.24],[2900,.07]]){const filter=ctx.createBiquadFilter(),gain=ctx.createGain();filter.type='bandpass';filter.frequency.setValueAtTime(freq*pitch,t+offset);filter.frequency.linearRampToValueAtTime(freq*pitch*.87,t+offset+duration);filter.Q.value=5;gain.gain.setValueAtTime(0,t);gain.gain.setValueAtTime(0,t+offset);gain.gain.linearRampToValueAtTime(amp,t+offset+.02);gain.gain.linearRampToValueAtTime(0,t+offset+duration);env.connect(filter);filter.connect(gain);gain.connect(this.master);}offset+=duration;}env.gain.setValueAtTime(.42,t);env.gain.exponentialRampToValueAtTime(.001,t+offset+.03);osc.start(t);osc.stop(t+offset+.04);this.burst(.07,.19,3500);}
 ping(win=false){if(!this.ctx)return;const t=this.ctx.currentTime;for(let i=0;i<(win?5:2);i++){const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='triangle';o.frequency.value=[293.66,369.99,440,587.33,739.99][i];g.gain.setValueAtTime(0,t+i*.09);g.gain.linearRampToValueAtTime(.12,t+i*.09+.01);g.gain.exponentialRampToValueAtTime(.001,t+i*.09+.34);o.connect(g);g.connect(this.master);o.start(t+i*.09);o.stop(t+i*.09+.36);}}
 warning(){if(!this.ctx)return;const t=this.ctx.currentTime;const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='triangle';o.frequency.setValueAtTime(180,t);o.frequency.linearRampToValueAtTime(340,t+.3);g.gain.setValueAtTime(.09,t);g.gain.exponentialRampToValueAtTime(.001,t+.4);o.connect(g);g.connect(this.master);o.start();o.stop(t+.45);}
}
