import * as THREE from 'three';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {SSAOPass} from 'three/addons/postprocessing/SSAOPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {ShaderPass} from 'three/addons/postprocessing/ShaderPass.js';
import {createState,step,MAPS} from './sim.js';
import {buildWorld} from './world.js';
import {configureArt,material,clay,roundedBox,label,createCharacter,drawFace,speech,canvasTexture,disposeObject} from './art.js';
import {GameAudio} from './audio.js';
import {controllerOwners} from './controls.js';
import {fitArenaDistance} from './camera.js';
import {createSky} from './sky.js';

const $=id=>document.getElementById(id),clamp=THREE.MathUtils.clamp;
const ui={menu:$('menu'),hud:$('hud'),remaining:$('remaining'),chaos:$('chaos-time'),chaosPill:$('chaos-pill'),announcement:$('announcement'),winner:$('winner'),name:$('winner-name'),restart:$('restart-text'),performance:$('performance')};
const audio=new GameAudio();let scene,camera,renderer,composer,ssao,world,state,characters=[],mapIndex=0,inGame=false,paused=false,accumulator=0,last=performance.now(),realTime=0,endAt=0,round=0,shake=0,kick=0,announceUntil=0,lastWarning='',showPerformance=false,selectedOutfit=1;
const keys=new Set(),pressed=new Set(),mouse=new THREE.Vector2(),raycaster=new THREE.Raycaster(),floorPlane=new THREE.Plane(new THREE.Vector3(0,1,0),0),aimPoint=new THREE.Vector3(),look=new THREE.Vector3(0,.7,0),camGoal=new THREE.Vector3(),cameraDirection=new THREE.Vector3(.10,.72,1).normalize();let mouseMoved=false;const propViews=new Map(),powerViews=new Map(),puddleViews=new Map(),particles=[],rings=[];let keyLight,fillLight,ambient;
let fpsFrames=0,fpsTime=0,fps=0,drawCalls=0,triangles=0;const frameTimes=[];
const MAP_NAMES=['ÇATI','MİNİBÜS','DÜĞÜN','İNTERNET KAFE','METRO','PARK'];
const EVENT_NAMES={earthquake:'DEPREM! AYAKTA KAL.',wind:'RÜZGÂR GELİYOR',boxes:'KAFANA DİKKAT!',lurch:'SIKI TUTUN!',slick:'YERLER KAYIYOR',blackout:'ELEKTRİKLER GİTTİ',rooftop:'RÜZGÂRA DİKKAT',minibus:'ŞOFÖR FRENE BASTI!',metro:'TREN GELİYOR!',park:'SALINCAĞA DİKKAT',wedding:'PİST KARIŞIYOR',cafe:'KAFELERDE BİR GECE'};
const helpers={roundedBox,material,label};
function init(){
 renderer=new THREE.WebGLRenderer({canvas:$('view'),antialias:true,powerPreference:'high-performance'});configureArt(renderer);renderer.setPixelRatio(devicePixelRatio);renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.info.autoReset=false;
 scene=new THREE.Scene();scene.userData.darkBackground=new THREE.Color(0x030706);scene.userData.sky=createSky();scene.background=scene.userData.sky;scene.fog=new THREE.FogExp2(0xc3bba9,.006);camera=new THREE.PerspectiveCamera(40,innerWidth/innerHeight,.15,260);camera.position.set(8,20,28);camera.lookAt(0,0,0);
 ambient=new THREE.HemisphereLight(0xc7d5df,0x78634e,1.5);scene.add(ambient);keyLight=new THREE.DirectionalLight(0xffc58c,4.5);keyLight.position.set(-11,19,-9);keyLight.castShadow=true;keyLight.shadow.mapSize.set(2048,2048);keyLight.shadow.camera.left=-16;keyLight.shadow.camera.right=16;keyLight.shadow.camera.top=14;keyLight.shadow.camera.bottom=-14;keyLight.shadow.camera.near=.5;keyLight.shadow.camera.far=60;keyLight.shadow.bias=-.0003;keyLight.shadow.normalBias=.035;keyLight.shadow.radius=4;scene.add(keyLight);fillLight=new THREE.DirectionalLight(0xc1d9e4,.8);fillLight.position.set(10,10,14);scene.add(fillLight);
 const renderTarget=new THREE.WebGLRenderTarget(innerWidth,innerHeight,{type:THREE.HalfFloatType,samples:4});composer=new EffectComposer(renderer,renderTarget);composer.addPass(new RenderPass(scene,camera));ssao=new SSAOPass(scene,camera,Math.ceil(innerWidth*.5),Math.ceil(innerHeight*.5),12);ssao.kernelRadius=.85;ssao.minDistance=.001;ssao.maxDistance=.12;composer.addPass(ssao);const bloom=new UnrealBloomPass(new THREE.Vector2(innerWidth*.5,innerHeight*.5),.17,.4,1.8);composer.addPass(bloom);composer.addPass(new OutputPass());
 const grade=new ShaderPass({uniforms:{tDiffuse:{value:null},tDepth:{value:ssao.normalRenderTarget.depthTexture},time:{value:0},resolution:{value:new THREE.Vector2(innerWidth*devicePixelRatio,innerHeight*devicePixelRatio)}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`uniform sampler2D tDiffuse,tDepth;uniform float time;uniform vec2 resolution;varying vec2 vUv;float noise(vec2 p){return fract(sin(dot(p,vec2(12.9898,78.233))+time)*43758.5453);}void main(){vec2 p=vUv-.5;float edge=dot(p,p);vec2 d=p*edge*.0012;float depth=texture2D(tDepth,vUv).x;float distance=.15*260./(260.-depth*(260.-.15));float coc=smoothstep(33.,85.,distance)*1.6;vec2 b=vec2(coc)/resolution;vec3 c=texture2D(tDiffuse,vUv).rgb*.4;c+=(texture2D(tDiffuse,vUv+vec2(b.x,b.y)).rgb+texture2D(tDiffuse,vUv+vec2(-b.x,b.y)).rgb+texture2D(tDiffuse,vUv+vec2(b.x,-b.y)).rgb+texture2D(tDiffuse,vUv-b).rgb)*.15;c.r=mix(c.r,texture2D(tDiffuse,vUv+d).r,.25);c.b=mix(c.b,texture2D(tDiffuse,vUv-d).b,.25);float l=dot(c,vec3(.2126,.7152,.0722));c=mix(vec3(l),c,.97);c+=vec3(.017,.007,-.009)*l;c+=vec3(-.005,.002,.006)*(1.-l);c*=1.-edge*.22;c+=(noise(gl_FragCoord.xy)-.5)*.018;gl_FragColor=vec4(c,1.);}`});composer.addPass(grade);scene.userData.grade=grade;
 setupMaps();loadMap(0);resize();bind();requestAnimationFrame(frame);$('loading').style.opacity='0';setTimeout(()=>$('loading').style.display='none',550);
}
function setupMaps(){for(let i=0;i<MAP_NAMES.length;i++){const b=document.createElement('button');b.className='map'+(!i?' active':'');b.textContent=MAP_NAMES[i];b.type='button';b.dataset.map=i;b.addEventListener('click',()=>{mapIndex=i;document.querySelectorAll('.map').forEach((e,j)=>e.classList.toggle('active',i===j));loadMap(i);});$('maps').appendChild(b);}}
function disposeView(v){scene.remove(v);disposeObject(v);}
function loadMap(index){
 document.querySelectorAll('.map').forEach((element,i)=>element.classList.toggle('active',i===index));
 clearTimeout(toastTimeout);$('toast').classList.remove('show');ui.announcement.classList.remove('show');
 if(world){scene.remove(world.group);world.dispose?.();}for(const c of characters){scene.remove(c.root,c.shadow,c.ring,c.name);c.dispose();}characters=[];for(const v of propViews.values())disposeView(v);propViews.clear();for(const v of powerViews.values())disposeView(v);powerViews.clear();for(const v of puddleViews.values())scene.remove(v);puddleViews.clear();for(const p of particles)scene.remove(p.mesh);particles.length=0;for(const r of rings)disposeView(r.mesh);rings.length=0;
 mapIndex=index;state=createState(45679+round*123,index);state.players[0].name=$('nickname').value.trim()||'Misafir';const other=state.players.find(p=>p.id!==0&&p.archetype===selectedOutfit);if(other)other.archetype=1;state.players[0].archetype=selectedOutfit;state.players.forEach(p=>{if(!inGame)p.bot=true;});if(inGame&&$('two-player').checked){state.players[1].bot=false;state.players[1].name='Komşu';}world=buildWorld(THREE,scene,index,helpers);if(!world.group.parent)scene.add(world.group);
 for(const p of state.players){const c=createCharacter(p);characters.push(c);scene.add(c.root,c.shadow,c.ring,c.name);drawFace(c,'idle');}
 $('location').textContent=`0${index+1} / ${['İSTANBUL ÇATILARI','SON DURAK: KAOS','ALTIN MAKAS DÜĞÜN SALONU','SON SAAT İNTERNET KAFE','AYRILIK ÇEŞMESİ','MAHALLE PARKI'][index]}`;
 const colors=[0xc3bba9,0xadb5ad,0x99988b,0x899b9e,0x8d9fa5,0xabc2b0];scene.background=index===0||index===1||index===5?scene.userData.sky:new THREE.Color(colors[index]);scene.fog.color.set(colors[index]);scene.userData.normalBackground=scene.background;audio.setMap(index);endAt=0;ui.winner.style.display='none';lastWarning='';accumulator=0;
}
function start(){inGame=true;paused=false;round++;ui.menu.classList.add('hidden');ui.menu.inert=true;ui.hud.style.display='flex';document.body.classList.add('in-game');$('home').style.display='block';$('play').blur();audio.start(mapIndex);loadMap(mapIndex);const fit=fitArenaDistance(camera.aspect,40,cameraDirection,look);if(camera.position.distanceTo(look)<fit)camera.position.copy(cameraDirection).multiplyScalar(fit).add(look);announce('BAĞIR. İT. AYAKTA KAL.',2.5);try{localStorage.setItem('siktr-nickname',$('nickname').value);}catch{}}
function goHome(){inGame=false;paused=false;$('pause').style.display='none';ui.menu.classList.remove('hidden');ui.menu.inert=false;ui.hud.style.display='none';document.body.classList.remove('in-game');$('home').style.display='none';loadMap(mapIndex);keyLight.intensity=4.5;ambient.intensity=1.5;fillLight.intensity=.8;}
function bind(){
 const outfit=document.createElement('button');outfit.id='outfit';outfit.type='button';outfit.textContent='AMCA ↻';outfit.title='Karakter değiştir';outfit.style.cssText='background:transparent;border:0;color:#ebcc93;padding:0;font-size:10px;cursor:pointer;font-weight:700;';$('pad-status').replaceWith(outfit);outfit.addEventListener('click',()=>{selectedOutfit=(selectedOutfit+1)%7;outfit.textContent=['ŞOFÖR','AMCA','ÖĞRENCİ','TEYZE','KURYE','MEMUR','KAFECİ'][selectedOutfit]+' ↻';loadMap(mapIndex);});
 try{const stored=localStorage.getItem('siktr-nickname');if(stored)$('nickname').value=stored;}catch{}
 $('play-form').addEventListener('submit',e=>{e.preventDefault();if(inGame)return;$('nickname').blur();start();});$('two-player').addEventListener('change',()=>{$('local-note').style.display=$('two-player').checked?'block':'none';});$('sound').addEventListener('click',()=>{const muted=audio.toggle();$('sound').textContent=muted?'♪̸':'♫';$('sound').setAttribute('aria-label',muted?'Sesi aç':'Sesi kapat');});$('home').addEventListener('click',goHome);$('resume').addEventListener('click',togglePause);
 window.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement)return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Slash'].includes(e.code)||(e.code==='Enter'&&inGame&&!paused))e.preventDefault();if(!keys.has(e.code))pressed.add(e.code);keys.add(e.code);if(e.code==='Escape'&&inGame&&!e.repeat)togglePause();if(e.code==='F3'){e.preventDefault();showPerformance=!showPerformance;ui.performance.style.display=showPerformance?'block':'none';}});
 window.addEventListener('keyup',e=>{keys.delete(e.code);});window.addEventListener('blur',()=>{keys.clear();pressed.clear();});document.addEventListener('visibilitychange',()=>{last=performance.now();accumulator=0;keys.clear();pressed.clear();});window.addEventListener('resize',resize);$('view').addEventListener('pointermove',e=>{mouse.set(e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2);mouseMoved=true;});window.addEventListener('gamepadconnected',()=>toast('Oyun kolu bağlandı · Sol çubuk yürü · A bağır · X kafa'));
}
function togglePause(){paused=!paused;$('pause').style.display=paused?'flex':'none';keys.clear();pressed.clear();last=performance.now();accumulator=0;}
function resize(){if(!renderer)return;renderer.setPixelRatio(devicePixelRatio);renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();composer.setPixelRatio(devicePixelRatio);composer.setSize(innerWidth,innerHeight);ssao.setSize(Math.ceil(innerWidth*devicePixelRatio*.5),Math.ceil(innerHeight*devicePixelRatio*.5));scene.userData.grade.uniforms.resolution.value.set(innerWidth*devicePixelRatio,innerHeight*devicePixelRatio);}
function humanInput(p,second=false){
 let x=0,z=0;if(second){x=+keys.has('ArrowRight')-+keys.has('ArrowLeft');z=+keys.has('ArrowDown')-+keys.has('ArrowUp');}else{x=+keys.has('KeyD')-+keys.has('KeyA');z=+keys.has('KeyS')-+keys.has('KeyW');}const a=Math.atan2(cameraDirection.x,cameraDirection.z);let wx=x*Math.cos(a)+z*Math.sin(a),wz=z*Math.cos(a)-x*Math.sin(a);const len=Math.hypot(wx,wz);if(len>1){wx/=len;wz/=len;}let angle=p.angle;if(second||!mouseMoved){if(len>.01)angle=Math.atan2(wx,wz);}else{raycaster.setFromCamera(mouse,camera);if(raycaster.ray.intersectPlane(floorPlane,aimPoint))angle=Math.atan2(aimPoint.x-p.x,aimPoint.z-p.z);}
 return{x:wx,z:wz,angle,shout:keys.has(second?'Enter':'Space')||pressed.has(second?'Enter':'Space'),butt:keys.has(second?'Slash':'ShiftLeft')||pressed.has(second?'Slash':'ShiftLeft')||(!second&&keys.has('ShiftRight')),grab:pressed.has(second?'Comma':'KeyQ'),throw:pressed.has(second?'Period':'KeyE')};
}
let previousPads={},owners=[];
function inputs(){
 const result={};if(!inGame)return result;const pads=Array.from(navigator.getGamepads?.()||[]).filter(Boolean);owners=controllerOwners(pads.map(p=>p.index),$('two-player').checked,owners);
 for(let i=0;i<state.players.length;i++){
  const p=state.players[i],owner=owners[i];p.bot=owner.kind==='bot';if(p.bot)continue;
  if(owner.kind==='keyboard'){result[p.id]=humanInput(p,owner.index===1);continue;}
  const pad=pads.find(p=>p.index===owner.index);if(!pad)continue;const dead=v=>Math.abs(v)>.17?v:0,x=dead(pad.axes[0]),z=dead(pad.axes[1]),a=Math.atan2(cameraDirection.x,cameraDirection.z),rx=dead(pad.axes[2]||0),rz=dead(pad.axes[3]||0),old=previousPads[pad.index]||[];
  result[p.id]={x:x*Math.cos(a)+z*Math.sin(a),z:z*Math.cos(a)-x*Math.sin(a),angle:rx||rz?Math.atan2(rx*Math.cos(a)+rz*Math.sin(a),rz*Math.cos(a)-rx*Math.sin(a)):x||z?Math.atan2(x*Math.cos(a)+z*Math.sin(a),z*Math.cos(a)-x*Math.sin(a)):p.angle,shout:pad.buttons[0]?.pressed,butt:pad.buttons[2]?.pressed,grab:pad.buttons[4]?.pressed&&!old[4],throw:pad.buttons[5]?.pressed&&!old[5]};previousPads[pad.index]=pad.buttons.map(b=>b.pressed);
 }
 for(const id of Object.keys(previousPads))if(!pads.some(p=>p.index===+id))delete previousPads[id];return result;
}
function announce(text,duration=2){ui.announcement.textContent=text;ui.announcement.classList.add('show');announceUntil=realTime+duration;}
let toastTimeout;function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>$('toast').classList.remove('show'),3000);}
const dustGeo=new THREE.IcosahedronGeometry(.065,0),dustMat=new THREE.MeshStandardMaterial({color:0xc6af85,roughness:1});
function burst(x,y,z,force=5){for(let i=0;i<Math.min(12,4+force);i++){if(particles.length>130)break;const m=new THREE.Mesh(dustGeo,dustMat);m.position.set(x,y+.25,z);scene.add(m);particles.push({mesh:m,vx:(Math.random()-.5)*3,vz:(Math.random()-.5)*3,vy:1+Math.random()*3,life:.3+Math.random()*.4});}}
function shoutRing(p){const geo=new THREE.RingGeometry(.65,.72,32,1,-Math.PI*.25,Math.PI*.5);const mat=new THREE.MeshBasicMaterial({color:0xffe1a0,transparent:true,opacity:.65,side:THREE.DoubleSide,depthWrite:false});const m=new THREE.Mesh(geo,mat);m.rotation.x=-Math.PI/2;m.rotation.z=-p.angle+Math.PI/2;m.position.set(p.x,.09,p.z);scene.add(m);rings.push({mesh:m,life:.45});}
function events(){for(const e of state.events||[]){const p=state.players[e.player],char=characters[e.player];if(e.type==='shout'){if(char)speech(char,e.text||'SIKTR!',realTime);if(p)shoutRing(p);if(inGame)audio.voice(e.text||'SIKTR!',p?.archetype||0);kick=Math.max(kick,1.3);}if(e.type==='impact'||e.type==='headbutt'||e.type==='throw'){shake=Math.max(shake,Math.min(.2,(e.force||4)*.008));kick=Math.max(kick,4);burst(e.x||p?.x||0,e.y||0,e.z||p?.z||0,e.force||5);if(inGame)audio.impact(e.force||5);}if(e.type==='eliminate'){if(inGame){toast((p?.name||'Biri')+' aşağıya selam söyledi.');audio.burst(.2,.25,650);}if(char)drawFace(char,'dead');}if(e.type==='powerup'&&inGame){audio.ping();if(p?.id===0)toast({megaphone:'MEGAFON · Sesin üç kat güçlü!',slipper:'TERLİK · Tek kafayla mahalleyi dağıt.',tea:'ÇAY · Arkanda kaygan iz bırak.',doner:'DÖNER · Dengen yerine geldi.'}[e.power||e.text||p?.power?.type]||'Güç seninle!');}if(e.type==='chaos'&&inGame)audio.warning();}}
function makeProp(p){const g=new THREE.Group(),wood=material('wood',0x8a6747),red=material('paint',0x9d4434),dark=material('metal',0x535955);const add=(w,h,d,r,m,x,y,z)=>{const o=roundedBox(w,h,d,r,m);o.position.set(x,y,z);g.add(o);return o;};if(p.type==='chair'){add(.72,.12,.74,.06,red,0,.65,0);add(.73,.66,.11,.08,red,0,1.05,-.31);for(const x of [-.26,.26])for(const z of [-.26,.26])add(.07,.66,.07,.025,red,x,.32,z);}else if(p.type==='table'){add(1.6,.14,1.05,.1,wood,0,.95,0);for(const x of [-.64,.64])for(const z of [-.37,.37])add(.09,.92,.09,.03,dark,x,.47,z);}else if(p.type==='monitor'){add(.78,.58,.46,.09,material('paint',0xb4af93),0,.48,0);const screen=roundedBox(.63,.40,.025,.02,new THREE.MeshStandardMaterial({color:0x246e6c,emissive:0x326d62,emissiveIntensity:.45,roughness:.35}));screen.position.set(0,.50,.24);g.add(screen);add(.5,.08,.35,.03,dark,0,.1,0);add(.12,.22,.12,.02,dark,0,.21,0);}else{add(.68,.68,.68,.06,wood,0,.34,0);for(const z of [-.346,.346])for(const y of [.08,.58])add(.7,.085,.025,.01,material('wood',0x513e2c),0,y,z);}scene.add(g);return g;}
function makePower(p){const g=new THREE.Group(),gold=clay(0xf7bf47);if(p.type==='megaphone'){const cone=new THREE.Mesh(new THREE.CylinderGeometry(.31,.12,.48,20,1,true),clay(0xdfd6bc));cone.rotation.x=Math.PI/2;g.add(cone);const grip=roundedBox(.11,.32,.1,.03,gold);grip.position.set(0,-.2,.12);g.add(grip);const rim=new THREE.Mesh(new THREE.TorusGeometry(.3,.03,7,24),gold);rim.position.z=.24;g.add(rim);}else if(p.type==='slipper'){const sole=roundedBox(.28,.1,.63,.09,clay(0xd84b38));g.add(sole);const band=roundedBox(.29,.14,.21,.06,gold);band.position.set(0,.12,.04);g.add(band);}else if(p.type==='tea'){const glass=new THREE.Mesh(new THREE.CylinderGeometry(.16,.1,.4,14),new THREE.MeshPhysicalMaterial({color:0xc07022,roughness:.2,transparent:true,opacity:.84,clearcoat:.8}));g.add(glass);const saucer=new THREE.Mesh(new THREE.CylinderGeometry(.25,.22,.04,20),clay(0xead3b0));saucer.position.y=-.21;g.add(saucer);}else{const bread=new THREE.Mesh(new THREE.CapsuleGeometry(.16,.42,5,14),clay(0xdcb66d));bread.rotation.z=Math.PI/2;g.add(bread);for(let i=0;i<5;i++){const filling=roundedBox(.09,.06,.3,.03,clay(i%2?0x597b36:0x8b4934));filling.position.set((i-2)*.1,.07,0);g.add(filling);}}
 const ring=new THREE.Mesh(new THREE.TorusGeometry(.5,.015,6,32),new THREE.MeshBasicMaterial({color:0xf4d48b,transparent:true,opacity:.6}));ring.rotation.x=Math.PI/2;ring.position.y=-.55;g.add(ring);g.userData.ring=ring;scene.add(g);return g;}
function puddleTexture(){const c=document.createElement('canvas');c.width=c.height=256;const g=c.getContext('2d');g.fillStyle='#ffffff';g.beginPath();for(let i=0;i<=64;i++){const a=i/64*Math.PI*2,r=102+Math.sin(a*5)*10+Math.sin(a*9+1)*6;const x=128+Math.cos(a)*r,y=128+Math.sin(a)*r;i?g.lineTo(x,y):g.moveTo(x,y);}g.closePath();g.fill();return canvasTexture(c);}
const puddleMat=new THREE.MeshPhysicalMaterial({color:0x86774a,map:puddleTexture(),roughness:.17,metalness:0,clearcoat:1,transparent:true,opacity:.40,depthWrite:false,alphaTest:.01});const puddleGeo=new THREE.PlaneGeometry(2,2);
function updateObjects(dt){
 const liveProps=new Set((state.props||[]).map(p=>p.id));for(const[id,v]of propViews)if(!liveProps.has(id)){disposeView(v);propViews.delete(id);}
 for(const p of state.props||[]){let v=propViews.get(p.id);if(!v){v=makeProp(p);propViews.set(p.id,v);}v.visible=p.alive!==false;v.position.set(p.x,p.y,p.z);v.rotation.y=p.angle||0;if(p.broken){v.scale.set(.5,.26,.48);}if(p.y>.1){v.rotation.x+=(p.vx||1)*dt*.4;v.rotation.z+=(p.vz||1)*dt*.4;}else{v.rotation.x*=Math.exp(-dt*5);v.rotation.z*=Math.exp(-dt*5);}}
 const livePowers=new Set();for(const p of state.powerups||[]){livePowers.add(p.id);let v=powerViews.get(p.id);if(!v){v=makePower(p);powerViews.set(p.id,v);}v.visible=p.alive!==false;v.position.set(p.x,.95+Math.sin(realTime*2.6+p.id)*.10,p.z);v.rotation.y=realTime*.9;}
 for(const [id,v]of powerViews)if(!livePowers.has(id)){disposeView(v);powerViews.delete(id);}
 const livePuddles=new Set();for(let i=0;i<(state.puddles||[]).length;i++){const p=state.puddles[i],id=p.id??i;livePuddles.add(id);let v=puddleViews.get(id);if(!v){v=new THREE.Mesh(puddleGeo,puddleMat);v.rotation.x=-Math.PI/2;scene.add(v);puddleViews.set(id,v);}v.position.set(p.x,.028,p.z);const r=p.radius||.7;v.scale.set(r,r*.72,1);v.visible=(p.remaining??1)>0;}for(const [id,v]of puddleViews)if(!livePuddles.has(id)){scene.remove(v);puddleViews.delete(id);}
 for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;if(p.life<=0){scene.remove(p.mesh);particles.splice(i,1);continue;}p.vy-=9*dt;p.mesh.position.x+=p.vx*dt;p.mesh.position.z+=p.vz*dt;p.mesh.position.y+=p.vy*dt;p.mesh.scale.setScalar(Math.max(.01,p.life*1.8));}
 for(let i=rings.length-1;i>=0;i--){const r=rings[i];r.life-=dt;if(r.life<=0){scene.remove(r.mesh);r.mesh.geometry.dispose();r.mesh.material.dispose();rings.splice(i,1);continue;}r.mesh.scale.setScalar(1+(1-r.life/.45)*5);r.mesh.material.opacity=r.life;}
}
function renderCharacters(dt){for(let i=0;i<state.players.length;i++){const p=state.players[i],c=characters[i];c.root.visible=p.y>-18;c.root.position.set(p.x,p.y,p.z);const delta=THREE.MathUtils.euclideanModulo(p.angle-c.root.rotation.y+Math.PI,Math.PI*2)-Math.PI;c.root.rotation.y+=delta*(1-Math.exp(-dt*14));const speed=Math.hypot(p.vx,p.vz);c.stride+=speed*dt*2.7;const rag=clamp(p.ragdoll||0,0,1),air=p.y>.2,walk=Math.sin(c.stride)*Math.min(.6,speed*.10);const seg=p.segments||[];const s=(j,k)=>clamp(seg[j]?.[k]||0,-1.4,1.4);
 c.torso.rotation.x=s(0,'rx')*.85+Math.cos(p.angle)*speed*.013+rag*Math.cos(p.id*2.4)*.75;c.torso.rotation.z=s(0,'rz')*.85-Math.sin(p.angle)*speed*.012+rag*Math.sin(p.id*2.4)*.8;c.torso.position.y=1.03-Math.min(.40,rag*.4)+Math.abs(Math.sin(c.stride))*Math.min(.08,speed*.014);c.headRig.rotation.x=s(1,'rx')*.65;c.headRig.rotation.z=s(1,'rz')*.65;c.head.scale.y=.55*(1-Math.min(.07,rag*.06));
 for(let j=0;j<2;j++){const side=j===0?-1:1;c.arms[j].rotation.x=(p.holding?-1.1:Math.sin(c.stride+j*Math.PI)*Math.min(.35,speed*.07))+s(j+2,'rx')*.85;c.arms[j].rotation.z=side*(.18+rag*.7)+s(j+2,'rz')*.65;c.legs[j].rotation.x=walk*side*(1-rag*.4)+s(j+4,'rx')*.7;c.legs[j].rotation.z=side*rag*.16+s(j+4,'rz')*.45;}
 c.torso.scale.set(1+Math.abs(walk)*.1,1-Math.abs(walk)*.08,1+Math.abs(walk)*.06);if(p.shoutCd>1){c.arms[0].rotation.z=-.95;c.arms[1].rotation.z=.95;c.headRig.rotation.x=-.2;}if(p.buttActive>0)c.torso.rotation.x=-.85;if(!p.alive){c.bodyRig.rotation.z+=dt*.7;c.bodyRig.rotation.x+=dt*.8;}else if(p.heldBy!==null&&p.heldBy!==undefined){c.bodyRig.rotation.z=THREE.MathUtils.lerp(c.bodyRig.rotation.z,1.3,1-Math.exp(-dt*8));c.bodyRig.rotation.x=Math.sin(realTime*5+p.id)*.35;}else{const forward=p.vx*Math.sin(p.angle)+p.vz*Math.cos(p.angle),sideways=p.vx*Math.cos(p.angle)-p.vz*Math.sin(p.angle),blend=1-Math.exp(-dt*5);c.bodyRig.rotation.x=THREE.MathUtils.lerp(c.bodyRig.rotation.x,clamp(forward*.10,-.75,.75)*rag,blend);c.bodyRig.rotation.z=THREE.MathUtils.lerp(c.bodyRig.rotation.z,-clamp(sideways*.13,-.9,.9)*rag,blend);}
 const expression=!p.alive?'dead':air?'panic':p.shoutCd>1?'shout':p.stagger>.05?'angry':Math.sin(realTime*.85+i*1.7)>.993?'blink':'idle';drawFace(c,expression);c.shadow.visible=p.alive&&Math.abs(p.x)<8.6&&Math.abs(p.z)<6.6;c.shadow.position.set(p.x,.017,p.z);c.shadow.material.opacity=.5/(1+Math.max(0,p.y)*1.7);c.shadow.scale.setScalar(1+Math.max(0,p.y)*.2);c.ring.visible=inGame&&!p.bot&&p.alive&&p.y<1;c.ring.position.set(p.x,.028,p.z);c.ringMat.opacity=p.shoutCd>0?.2:.8;c.name.visible=inGame&&p.alive&&!p.bot;c.name.position.set(p.x,p.y+2.7,p.z);c.name.quaternion.copy(camera.quaternion);c.bubble.visible=realTime<c.bubbleUntil;c.bubble.position.y=2.8+Math.sin(realTime*7)*.035;
}}
function updateCamera(dt){const living=state.players.filter(p=>p.alive&&p.y>-2);let cx=0,cz=0;for(const p of living){cx+=p.x;cz+=p.z;}cx/=living.length||1;cz/=living.length||1;const menuShift=inGame?0:-2.8;const target=new THREE.Vector3(clamp(cx*.09,-.65,.65)+menuShift,.9,clamp(cz*.08,-.5,.5));look.lerp(target,1-Math.exp(-dt*2));let dist=inGame?fitArenaDistance(camera.aspect,40,cameraDirection,look):Math.max(24,23/(camera.aspect*.87));camGoal.copy(cameraDirection).multiplyScalar(dist).add(look);camera.position.lerp(camGoal,1-Math.exp(-dt*2.8));if(shake>.002){camera.position.x+=Math.sin(realTime*119)*shake;camera.position.y+=Math.cos(realTime*87)*shake*.7;}shake*=Math.exp(-dt*23);kick*=Math.exp(-dt*13);camera.fov=40+kick;camera.updateProjectionMatrix();camera.lookAt(look);}
function updateHUD(){if(!inGame)return;ui.remaining.textContent=state.players.filter(p=>p.alive).length;const chaos=state.chaos||{};let until=typeof chaos.next==='number'?Math.max(0,chaos.next-state.time):30-state.time%30;ui.chaos.textContent='00:'+String(Math.ceil(until)).padStart(2,'0');const warning=chaos.warning>0||state.hazard?.warning>0;ui.chaosPill.classList.toggle('warn',warning);const which=chaos.warning>0?chaos.type:state.hazard?.warning>0?state.hazard.type:'';if(which){const countdown=Math.ceil(chaos.warning>0?chaos.warning:state.hazard.warning),message=(EVENT_NAMES[which]||'DİKKAT! ORTALIK KARIŞACAK.')+' · '+countdown;if(lastWarning!==which){announce(message,3);audio.warning();}else ui.announcement.textContent=message;}lastWarning=which||'';const blackout=chaos.active&&chaos.type==='blackout';scene.background=blackout?scene.userData.darkBackground:scene.userData.normalBackground;keyLight.intensity=blackout?.04:4.5;ambient.intensity=blackout?.04:1.5;fillLight.intensity=blackout?.03:.8;
 if(state.phase==='finished'){if(!endAt){endAt=realTime+5;ui.winner.style.display='flex';const winner=state.players.find(p=>p.id===state.winner);ui.name.textContent=winner?winner.name.toLocaleUpperCase('tr-TR'):'KİMSE KALMADI';audio.ping(true);}ui.restart.textContent=`Yeni raund ${Math.max(1,Math.ceil(endAt-realTime))} saniye içinde`;if(realTime>=endAt){round++;mapIndex=(mapIndex+1)%6;loadMap(mapIndex);announce('YENİ MEKÂN. AYNI MESELE.',2);}}
}
function frame(now){requestAnimationFrame(frame);const elapsed=(now-last)/1000,dt=Math.min(.05,elapsed);last=now;if(document.hidden)return;if(!paused){realTime+=dt;const slow=state.phase==='finished'?.35:(state.slowmo||1);accumulator+=dt*(inGame?slow:.45);let n=0;while(accumulator>=1/60&&n<5){step(state,inputs(),1/60);events();accumulator-=1/60;n++;pressed.clear();}if(!inGame&&state.phase==='finished'){round++;loadMap(mapIndex);}world.update(state,state.time);renderCharacters(dt);updateObjects(dt);updateCamera(dt);updateHUD();if(realTime>announceUntil)ui.announcement.classList.remove('show');}
 scene.userData.grade.uniforms.time.value=now*.001;renderer.info.reset();composer.render();fpsFrames++;fpsTime+=elapsed;frameTimes.push(elapsed*1000);if(frameTimes.length>300)frameTimes.shift();if(fpsTime>=1){fps=fpsFrames/fpsTime;drawCalls=renderer.info.render.calls;triangles=renderer.info.render.triangles;fpsFrames=0;fpsTime=0;ui.performance.textContent=`${fps.toFixed(0)} FPS · ${(1000/fps).toFixed(1)} ms\n${drawCalls} calls · ${(triangles/1000).toFixed(0)}k tris\n${renderer.domElement.width} × ${renderer.domElement.height}\n60 Hz simulation · ${state.tick} ticks\n${state.players.filter(p=>p.alive).length} alive · ${state.time.toFixed(1)}s`;}
}
try{init();}catch(error){console.error(error);$('loading-message').classList.add('error');$('loading-message').textContent='Oyun başlatılamadı: '+error.message+' — WebGL 2 destekli güncel bir tarayıcı kullan.';}
